schema {
    query: Query
    mutation: Mutation
}

type Query {
    get_student(id: String!): Response!
}

type Mutation {
    add_student(student: StudentInput!): Response!
}

input StudentInput {
    name: String!
    age: Int!
    dept: String!
}

type Response {
    student: Student
    success: Message
    error: Message
}

type Student {
    id: Int!
    name: String!
    age: Int!
    dept: String!
}

type Message {
    status_code: Int!
    message: String!
}
