type Execution {
	output: String
	status: String
	# input: String
	# name: String
	# executionArn: String
	# startDate: String
	# stopDate: String
}

type Mutation {
	# Start a state machine execution by providing input and name
	addStudent(step: Int!): Execution
	getStudent(step: Int!): Execution
}

# type Subscription {
# 	onStartExecution: Execution
# 		@aws_subscribe(mutations: ["addStudent"])
# }

# input StartExecutionInput {
# 	input: String!
# }

type Query {
	listExecutions: [Execution]
		@deprecated(
			reason: "Express workflows do not support ListExecutions or DescribeExecution"
		)
}

schema {
	query: Query
	mutation: Mutation
	# subscription: Subscription
}
