import * as cdk from '@aws-cdk/core';
import * as secretsmanager from '@aws-cdk/aws-secretsmanager';
import * as lambda from '@aws-cdk/aws-lambda';

export class Example00CreateAutoSecretStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // The code that defines your stack goes here

    const secretDefined = new secretsmanager.Secret(this, 'secretDefined', {
      secretName: 'ahmed-faraz',
    });
    const secretAutoGenerated = new secretsmanager.Secret(this, 'secretAutoGenerated');

    const lambdaFunc = new lambda.Function(this, 'lambdaFuncForSecretsManager',{
      runtime: lambda.Runtime.NODEJS_14_X,
      code: lambda.Code.fromAsset('lambda'),
      handler: 'index.handler',
      environment: {
        SECRET_DEFINED: `${
          secretsmanager.Secret.fromSecretNameV2(this, 'exampleKeyDefined', secretDefined.secretName).secretValue
        }`,
        SECRET_AUTO_GENERATED: `${
          secretsmanager.Secret.fromSecretAttributes(this, 'exampleKeyAutoGenerated', {
            secretArn: secretAutoGenerated.secretArn
          }).secretValue
        }`,
      }
    })
  }
}
