exports.handler = async () => {
    return {
        statusCode: 200,
        headers: { 'Content/Type' : 'text/plain' },
        body: `Hello, CDK! You've hit keys, [DefinedKey:${process.env.SECRET_DEFINED}] & [AutoGeneratedKey:${process.env.SECRET_AUTO_GENERATED}]`
    }
}