type Query {
  welcome: String
  products: [Product]
}

type Product {
  id: String
  title: String
  price: Int
}

input AddProductInput {
  title: String
  price: Int
}

input UpdateProductInput {
  id: String
  title: String
  price: Int
}

type Mutation {
  addProduct(product: AddProductInput): Product
  updateProduct(product: UpdateProductInput): Product
  deleteProduct(productID: String): String
}
